name: builder

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install podman
        run: |
          sudo apt update
          sudo apt-get -y install podman

      - name: Build podman container
        run: |
          podman build -f Containerfile -t live-build

      - name: Build ISO
        run: |
          sudo podman run --rm -it --privileged -v "$(pwd)":/build:exec,dev -w /build localhost/live-build sh -c './configure.sh && lb build'

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Meh
          fail_on_unmatched_files: yes
          files: |
            *.hybrid.iso
