name: builder

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-22.04

    container:
      image: debian:latest
      volumes:
        - /proc:/proc
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install live-build
        run: |
          apt update
          apt-get -y install live-build

      - name: Build ISO
        run: |
          ./configure.sh
          lb build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Meh
          fail_on_unmatched_files: yes
          files: |
            *.hybrid.iso

