name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:bullseye # specifically for glibc 2.31CARGO_TARGET_DIR

    steps:
    - uses: actions/checkout@v4

    - name: Rustup Get Toolchain
      run: rustup target add x86_64-unknown-linux-musl

    - name: Build Release
      run: |
        cargo build --verbose --release
        cargo build --verbose --release --target x86_64-unknown-linux-musl
        find . -name 'arcam'
        mv target/target/x86_64-unknown-linux-musl/release/arcam target/target/x86_64-unknown-linux-musl/release/arcam-musl

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          target/release/arcam
          target/target/x86_64-unknown-linux-musl/release/arcam-musl
